# Generated by Django 3.1.4 on 2021-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('OP', 'Operador'), ('GER', 'Gerente')], default='OP', max_length=3)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
