# Generated by Django 3.1.4 on 2021-01-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeStock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=3, null=True),
        ),
    ]
