# Generated by Django 3.1.4 on 2021-01-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeStock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('galpao', models.CharField(max_length=5)),
                ('corredor', models.CharField(max_length=5)),
                ('quantidade_prateleiras', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_url', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('descricao', models.CharField(max_length=350)),
                ('numero_prateleira', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRcodeStock.categoria', verbose_name='ID Categoria')),
                ('id_estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRcodeStock.estante', verbose_name='ID Estante')),
            ],
        ),
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_url', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('observacoes', models.CharField(max_length=100)),
                ('data_fabricacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRcodeStock.produto', verbose_name='ID Produto')),
            ],
        ),
    ]
