# Generated by Django 3.1.4 on 2021-01-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeStock', '0002_categoria_estante_produto_remessa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('observacoes', models.CharField(max_length=100)),
                ('data_fabricacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRcodeStock.produto', verbose_name='ID Produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Remessa',
        ),
    ]
