# Generated by Django 3.1.4 on 2021-01-05 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeStock', '0003_auto_20210104_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='id_usuario',
            field=models.ForeignKey(default='Desconhecido', on_delete=django.db.models.deletion.SET_DEFAULT, to='QRcodeStock.usuario', verbose_name='Usuario criador'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_categoria',
            field=models.ForeignKey(default='Sem categoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='QRcodeStock.categoria', verbose_name='ID Categoria'),
        ),
    ]
