# Generated by Django 3.1.4 on 2021-01-05 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeStock', '0005_auto_20210104_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='QRcodeStock.categoria', verbose_name='ID Categoria'),
        ),
    ]
