# Generated by Django 3.1.4 on 2021-01-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeStock', '0007_auto_20210104_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='num_prateleira',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='estante',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estante',
            name='corredor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estante',
            name='galpao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
